module.exports = [
  {
    key: process.env.TOKEN_1,
    discordID: "idk",
    nameColor: "#87ceeb",
    class: "developer",
    infiniteLevelUp: true,
    name: "Flowey",
    note: "F",
  },
  {
    key: process.env.TOKEN_2,
    discordID: "imnotgivingyouthisinformationlol",
    nameColor: "#00ff00",
    class: "developer",
    infiniteLevelUp: true,
    name: "MLG",
    note: "That one unofficial community manager from the sandbox server #wpd. Also a co-developer of tank-dev.glitch.me.",
  },
  {
    key: process.env.TOKEN_3,
    discordID: "0",
    nameColor: "#ffffff",
    class: "developer",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
  {
    key: process.env.TOKEN_4,
    discordID: "0",
    nameColor: "#ffffff",
    class: "developer",
    infiniteLevelUp: true,
    name: "unnamed#0000",
    note: "note here",
  },
];
